version: "3.8"

services:
  app:
    build:
      context: ./FlightLogNet
    image: flightlog/app
    ports:
      - "44313:44313"
    volumes:
      - dbData:/app/data/
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:44313

volumes:
  dbData:
